### PR TITLE
feat: introduce macos support

### PR DESCRIPTION
**Pull request by oowl**
sister PR: https://github.com/nix-rust/nix/pull/2347

### CODE REVIEW

**Comment by oowl** [comment]
let's waiting for https://github.com/nix-rust/nix/pull/2347 released!

**Comment by Xuanwo** [comment]
> let's wait for [nix-rust/nix#2347](https://github.com/nix-rust/nix/pull/2347) released!

New libc has been released: https://github.com/nix-rust/nix/pull/2398

**Comment by radumarias** [comment]
when is the plan for this to be completed? I'm eagerly waiting for it to use it in my encrypted filesystem app

**Comment by oowl** [comment]
> when is the plan for this to be completed? I'm eagerly waiting for it to use it in my encrypted filesystem app

I will push forward in these days, thank you for you to pay attention to it.

**Comment by SteveLauC** [comment]
Nix 0.29.0 has just been released, sorry for letting you guys wait for such a long time.

**Comment by radumarias** [comment]
Hi, how's it going with this? Would very much appreciate this being merged. I started developing GUI in Kotlin and starting with macos. So +1 for this :)

**Comment by radumarias** [comment]
@oowl sorry to keep pushing on this, but any news on when it will be merged? I'm eagerly waiting for this to integrate it in my app as I'm very close to a stable release and would be great to include this also

**Comment by radumarias** [comment]
@oowl any updates on this? I'm eagerly waiting to integrate it in my app :) Is there something I could help with?

**Comment by oowl** [comment]
Sorry for my lateness. It will finish in these days.

**Comment by radumarias** [comment]
no worries, great to hear that, thank you very much

**Comment by radumarias** [comment]
@oowl sorry to bother you again, any chance to get this in soon?

**Comment by oowl** [comment]
Recreate it as a new PR due to rebase hell.

**Pull request closed without merging**
